config:
  speex:
    container:
      - none
      - nuance_frame
    codec:
      - wb
      - nb
  opus:
    container:
      - nuance_frame
    codec:
      - 8k
      - 12k
      - 16k
      - 24k
      - 48k
  pcm:
    container:
      - none
    codec:
      - 8k
      - 16k
      - 32k